### ISSUE TITLE
Temperatures below 0°C

### ISSUE THREAD

**Issue by DrTron** [takagi/am2321#1]
Hello,

has the code been tested for temperatures below 0°C? Above that, I get correct readings, but below that I get readings like "temperature= -3276.-2".

**Comment by takagi** [comment]
No, I've not tested it below 0℃. It should be a bug on my code.

**Comment by DrTron** [comment]
Probably. I plan on using the sensor for outside temperatures, so negative values may arise (if you don't live at the equator or such)...I think the sensor itself is capable of measuring down to -40°C.

I haven't looked that deeply into the code, yet.

**Comment by takagi** [comment]
I fixed the interpretation of temperature (and humidity) on branch `issue/1`.

https://github.com/takagi/am2321/tree/issue/1

Could you test the fixed version because now I do not have environment to test it with actual am2321 sensor?

**Comment by takagi** [comment]
I assumed that the raw representation of temperature below zero is ordinal signed two bytes short multiplied by ten, which I could not find exact mention on the datasheet.

http://akizukidenshi.com/download/ds/aosong/AM2321_e.pdf

**Comment by DrTron** [comment]
Will certainly test it tonight, thanks for the code update. I don't know if it will be below freezing this winter again, though. I can't test the humidity reading, either, as a test with cold spray has probably wrecked the humidity part of the sensor.

**Comment by DrTron** [comment]
The code works, though I can't say if it will for temperatures below zero, though.
Btw., you could add a comment to the readme file that one needs to set the correct i2c device in the sourcecode. Newer Raspberry Pi's now use "/dev/i2c-1", for example, not "/dev/i2c-0".

**Comment by DrTron** [comment]
Nope, Problem not solved. I do get a valid reading now (no minus sign after the decimal) but the readings below zero are still "-3276.7 °C" - constant as far as I can see. I'll need to check the logfiles I write tonight to be sure.

But I found this in the technical specs: "Temperature resolution is 16Bit, temperature highest bit (Bit15) is equal to 1 indicates a negative temperature, the temperature highest bit (Bit15) is equal to 0 indicates a positive temperature; temperature in addition to the most significant bit (Bit14 ~ Bit0) indicates the temperature sensor string value. Temperature sensor value is a string of 10 times the actual temperature value."

I guess there needs to be a function to read that Bit15 and use that as a positive or negative value, cutting it off from the value first. Obviously that doesn't happen and that's why I get so strange values. Above zero that does not come into play as Bit15 is zero then. I guess it needs to go somewhere between lines 108-109 where the temperature is read from the raw data (If I assume correctly, I'm not a programmer).

**Comment by takagi** [comment]
> Btw., you could add a comment to the readme file that one needs to set the correct i2c device in the sourcecode. Newer Raspberry Pi's now use "/dev/i2c-1", for example, not "/dev/i2c-0".

Okay, I will mention about it on README.

**Comment by takagi** [comment]
> But I found this in the technical specs: "Temperature resolution is 16Bit, temperature highest bit (Bit15) is equal to 1 indicates a negative temperature, ...

Thanks! I will fix interpretation of temperature representation on this spec.

**Comment by takagi** [comment]
I fixed the branch `issue/1` so would you try it again? As far as I tested it with stub data with 23.4℃ with highest bit one, it printed `-23.4 [C]` as I expected.

**Comment by DrTron** [comment]
Sure. Don't know if we will experience sub-freezing temperatures again, though ;-)

**Comment by takagi** [comment]
Spring is coming.

**Comment by DrTron** [comment]
Works so far at temperatures above zero.

**Comment by takagi** [comment]
Thanks for letting me know it.

**Comment by DrTron** [comment]
Recently the temperature dipped briefly below zero overnight and I got the correct negative values. So it seems to work now and we can close this bug. Thanks a lot for fixing!

**Comment by takagi** [comment]
Okay!
